CREATE TYPE booking_status AS ENUM ('WAITING', 'APPROVED', 'REJECTED', 'CANCELLED');

CREATE TABLE IF NOT EXISTS items
(
    item_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name   varchar(80),
    description varchar(500),
    available boolean,
    owner_id int REFERENCES users (user_id),
    request_id int
);


CREATE TABLE IF NOT EXISTS users
(
    user_id       int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          varchar(80),
    email varchar(80) UNIQUE
);



CREATE TABLE IF NOT EXISTS bookings
(
    booking_id   int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    start_time timestamp without time zone,
    end_time timestamp without time zone,
    item_id int REFERENCES items (item_id),
    booker_id int REFERENCES users (user_id),
    status booking_status
);

CREATE TABLE IF NOT EXISTS requests
(
    request_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    items_id int REFERENCES items (item_id),
    description varchar(80),
    requester_id int REFERENCES users (user_id),
    created timestamp without time zone
);