DROP TYPE IF EXISTS booking_status cascade;
DROP TABLE IF EXISTS comments cascade;
DROP TABLE IF EXISTS requests cascade;
DROP TABLE IF EXISTS bookings cascade;
DROP TABLE IF EXISTS items cascade;
DROP TABLE IF EXISTS users cascade;

CREATE TYPE booking_status  AS ENUM ('WAITING', 'APPROVED', 'REJECTED', 'CANCELLED');

CREATE TABLE users
(
    user_id       int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          varchar(80),
    email varchar(80) UNIQUE
);

CREATE TABLE items
(
    item_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name   varchar(80),
    description varchar(500),
    available boolean,
    owner_id int REFERENCES users (user_id),
    request_id int
);

CREATE TABLE bookings
(
    booking_id   int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    start_time timestamp without time zone,
    end_time timestamp without time zone,
    item_id int REFERENCES items (item_id),
    booker_id int REFERENCES users (user_id),
    status booking_status
);

CREATE TABLE requests
(
    request_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description varchar(80),
    requester_id int REFERENCES users (user_id)
);

CREATE TABLE comments
(
    comment_id        int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    text      varchar(600),
    item_id   int REFERENCES items (item_id),
    author_id int REFERENCES users (user_id)
);